# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a7c51d30e9ec3a1bb0f1377099ed70dc"
name = "JewelSync"
application_url = "https://stallion-inviting-gnu.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app_subscriptions/update"
  topics = [ "app_subscriptions/update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://stallion-inviting-gnu.ngrok-free.app/auth/callback" ]

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

